
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 15 03:09:19 GFT 2015
//----------------------------------------------------

package com.language.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OPAEXP = 5;
  public static final int OPBMENOR = 20;
  public static final int DOSPUNTOS = 34;
  public static final int OPBABNOT = 12;
  public static final int PUNTOYCOMA = 31;
  public static final int OPBMAYOR = 21;
  public static final int FUNCION = 47;
  public static final int OPAMOD = 8;
  public static final int INTEGER = 52;
  public static final int CONTINUE = 42;
  public static final int LPAREN = 29;
  public static final int OPADIVENTERA = 7;
  public static final int OPBABSHIFTR = 14;
  public static final int DATAFUNCION = 46;
  public static final int LCORCHETE = 25;
  public static final int FOR = 43;
  public static final int OPBABSHIFTL = 13;
  public static final int OPBDISTINTO = 19;
  public static final int RPAREN = 30;
  public static final int NOT = 17;
  public static final int AND = 15;
  public static final int LLLAVE = 27;
  public static final int IN = 44;
  public static final int OR = 16;
  public static final int TAB = 55;
  public static final int RLLAVE = 28;
  public static final int IF = 38;
  public static final int NOTAB = 56;
  public static final int ID = 51;
  public static final int EOF = 0;
  public static final int RETURN = 48;
  public static final int ASIG = 24;
  public static final int OPAMENOS = 3;
  public static final int TRUE = 35;
  public static final int error = 1;
  public static final int OPAPROD = 4;
  public static final int COMA = 33;
  public static final int OPAMAS = 2;
  public static final int BREAK = 41;
  public static final int OPBMENORIGUAL = 22;
  public static final int NONE = 37;
  public static final int ELSE = 39;
  public static final int PUNTO = 32;
  public static final int WHILE = 40;
  public static final int OPBIGUAL = 18;
  public static final int OPBABDAND = 9;
  public static final int OPBMAYORIGUAL = 23;
  public static final int FLOAT = 54;
  public static final int RCORCHETE = 26;
  public static final int OPBABOR = 10;
  public static final int LONG = 53;
  public static final int STRING = 50;
  public static final int DEF = 45;
  public static final int FALSE = 36;
  public static final int OPBABXOR = 11;
  public static final int OPADIV = 6;
  public static final int PRINT = 49;
}

